"""DAG Domain Exception Hierarchy Module for Basalt Workflow Engine.

Provides explicit, structured exception classes for DAG parsing, schema validation,
cycle detection, orphan step dependency resolution, and execution errors.
"""

from typing import Any


class BasaltError(Exception):
    """Base exception class for all errors generated by the Basalt workflow engine."""

    def __init__(
        self,
        message: str,
        code: str = "INTERNAL_BASALT_ERROR",
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.details = details or {}

    def to_dict(self) -> dict[str, Any]:
        """Convert exception to dictionary representation for API responses and logs.

        Returns:
            Dictionary containing error code, message, and details context.
        """
        return {
            "error_code": self.code,
            "message": self.message,
            "details": self.details,
        }

    def __str__(self) -> str:
        if self.details:
            return f"[{self.code}] {self.message} (details: {self.details})"
        return f"[{self.code}] {self.message}"


class DAGError(BasaltError):
    """Base exception class for all DAG-related workflow errors."""

    def __init__(
        self,
        message: str,
        dag_id: str | None = None,
        code: str = "DAG_ERROR",
        details: dict[str, Any] | None = None,
    ) -> None:
        merged_details = details or {}
        if dag_id:
            merged_details["dag_id"] = dag_id
        super().__init__(message=message, code=code, details=merged_details)
        self.dag_id = dag_id


class DAGParseError(DAGError):
    """Raised when JSON or YAML workflow file parsing fails."""

    def __init__(
        self,
        message: str,
        filepath: str | None = None,
        dag_id: str | None = None,
        line_number: int | None = None,
    ) -> None:
        details: dict[str, Any] = {}
        if filepath:
            details["filepath"] = filepath
        if line_number:
            details["line_number"] = line_number
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="DAG_PARSE_ERROR",
            details=details,
        )
        self.filepath = filepath
        self.line_number = line_number


class DAGValidationError(DAGError):
    """Raised when DAG schema structure fails Pydantic validation rules."""

    def __init__(
        self,
        message: str,
        validation_errors: list[dict[str, Any]] | None = None,
        dag_id: str | None = None,
    ) -> None:
        details: dict[str, Any] = {}
        if validation_errors:
            details["validation_errors"] = validation_errors
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="DAG_VALIDATION_ERROR",
            details=details,
        )
        self.validation_errors = validation_errors or []


class CycleDetectedError(DAGError):
    """Raised when a circular dependency is detected in the step graph."""

    def __init__(
        self,
        cycle_path: list[str],
        dag_id: str | None = None,
    ) -> None:
        path_str = " -> ".join(cycle_path)
        message = f"Cyclic dependency detected in DAG step graph: {path_str}"
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="CYCLE_DETECTED",
            details={"cycle_path": cycle_path},
        )
        self.cycle_path = cycle_path


class OrphanDependencyError(DAGError):
    """Raised when a step depends on a non-existent upstream step ID."""

    def __init__(
        self,
        step_id: str,
        missing_dependency_id: str,
        dag_id: str | None = None,
    ) -> None:
        message = f"Step '{step_id}' references non-existent upstream dependency '{missing_dependency_id}'."
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="ORPHAN_DEPENDENCY",
            details={
                "step_id": step_id,
                "missing_dependency_id": missing_dependency_id,
            },
        )
        self.step_id = step_id
        self.missing_dependency_id = missing_dependency_id


class DuplicateStepIdError(DAGError):
    """Raised when multiple steps share the same step ID within a DAG."""

    def __init__(
        self,
        step_id: str,
        dag_id: str | None = None,
    ) -> None:
        message = f"Duplicate step ID '{step_id}' encountered in DAG definition."
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="DUPLICATE_STEP_ID",
            details={"step_id": step_id},
        )
        self.step_id = step_id


class InvalidExecutorConfigError(DAGError):
    """Raised when task executor parameters are missing or invalid."""

    def __init__(
        self,
        step_id: str,
        executor_type: str,
        reason: str,
        dag_id: str | None = None,
    ) -> None:
        message = (
            f"Invalid configuration for step '{step_id}' using executor '{executor_type}': {reason}"
        )
        super().__init__(
            message=message,
            dag_id=dag_id,
            code="INVALID_EXECUTOR_CONFIG",
            details={
                "step_id": step_id,
                "executor_type": executor_type,
                "reason": reason,
            },
        )
        self.step_id = step_id
        self.executor_type = executor_type
        self.reason = reason


class ExecutionTimeoutError(BasaltError):
    """Raised when a step or DAG execution exceeds its maximum allowed duration."""

    def __init__(
        self,
        message: str,
        timeout_seconds: float,
        elapsed_seconds: float,
        step_id: str | None = None,
        run_id: str | None = None,
    ) -> None:
        details = {
            "timeout_seconds": timeout_seconds,
            "elapsed_seconds": elapsed_seconds,
        }
        if step_id:
            details["step_id"] = step_id
        if run_id:
            details["run_id"] = run_id
        super().__init__(
            message=message,
            code="EXECUTION_TIMEOUT",
            details=details,
        )
        self.timeout_seconds = timeout_seconds
        self.elapsed_seconds = elapsed_seconds
        self.step_id = step_id
        self.run_id = run_id
